version: '3'

services:
  ackermann_sim:
    image: alitekes1/ackermann_sim:latest
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        ROS_DISTRO: jazzy
        GZ_VERSION: harmonic
    runtime: nvidia
    stdin_open: true
    tty: true
    environment: 
      - PYTHONUNBUFFERED=1
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - __NV_PRIME_RENDER_OFFLOAD=1
      - __GLX_VENDOR_LIBRARY_NAME=nvidia
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /run/user:/run/user:ro
      - ./src:/root/colcon_ws/src
      - ./configs:/root/colcon_ws/configs
      - ./scripts:/root/colcon_ws/scripts
      - ./data:/root/colcon_ws/data
      - ./artifacts:/root/colcon_ws/artifacts
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    container_name: ackermann_sim